<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Dyego Donadone</title>
        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/login.css" rel="stylesheet">
    </head>
    <body>
        <div class="pagina">
            <div class="container">
                <?php echo $this->form()->openTag($form->setAttribute('class', 'form')); ?>
                <div>
                    <h1>Painel de Controle</h1>
                </div>

                <?php
                    if (isset($this->error)) : ?>        
                        <div class="alert alert-danger alert-dismissable">
                            <p><?php echo $this->error; ?></p>
                        </div>
                        <?php
                    endif;

                    echo $this->formRow($form->get('usuario')
                        ->setAttribute('class', 'form-control col-lg-12')
                        ->setAttribute('placeholder', 'Usuario - Dyego')
                    );
                    
                    echo $this->formRow($form->get('senha')
                        ->setAttribute('class', 'form-control col-lg-12')
                        ->setAttribute('placeholder', 'Senha - qw123as')
                    );
                    
                    echo $this->formElement($form->get('send')->setAttribute('class', 'btn btn-info'));
                    echo $this->form()->closeTag() 
                ?>

            </div>
        </div>
    </body>
</html>
